export const ACTION_TYPE = {
  SET_OPERATOR_REQUEST: "SET_OPERATOR_REQUEST",
  SET_OPERATOR_SUCCESS: "SET_OPERATOR_SUCCESS",
  SET_OPERATOR_FAILURE: "SET_OPERATOR_FAILURE",
  LOGOUT: "LOGOUT",
  ADD_USER_REQUEST: "ADD_USER_REQUEST",
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  ADD_USER_FAILURE: "ADD_USER_FAILURE",
  FETCH_DATA_REQUEST: "FETCH_DATA_REQUEST",
  FETCH_DATA_SUCCESS: "FETCH_DATA_SUCCESS",
  FETCH_DATA_FAILURE: "FETCH_DATA_FAILURE",
};
